# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManage', '0002_auto_20170819_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compound',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compound_gene',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='functions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='organism',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='part_features',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='part_gene',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='part_papers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='part_parameters',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='part_twins',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pathway',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pathway_compound',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reaction_compound',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='team_parts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='track_functions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'managed': False},
        ),
    ]
