# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneRelationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('nicknames', models.TextField(null=True)),
                ('definition', models.TextField(null=True)),
                ('organism_short', models.CharField(max_length=16)),
                ('organism', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=16)),
                ('ntseq_length', models.IntegerField()),
                ('ntseq', models.TextField(null=True)),
            ],
            options={
                'db_table': 'bio_gene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='One_KeySentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name_one', models.CharField(max_length=64)),
                ('gene_name_two', models.CharField(max_length=64)),
                ('sentence', models.TextField()),
            ],
            options={
                'db_table': 'bio_one_keysentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper_Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=32)),
                ('paper_title', models.CharField(max_length=255)),
                ('paper_keyword', models.CharField(default=None, max_length=255)),
                ('paper_abstract', models.TextField()),
                ('paper_link', models.CharField(max_length=255)),
                ('paper_class', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'bio_paper_gene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Three_KeySentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name_one', models.CharField(max_length=64)),
                ('gene_name_two', models.CharField(max_length=64)),
                ('sentence', models.TextField()),
            ],
            options={
                'db_table': 'bio_three_keysentence',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='gene_disease',
            options={'managed': False},
        ),
    ]
